#!/usr/bin/env python
from sqlalchemy import create_engine
from sqlalchemy import MetaData
from sqlalchemy import Table, Column
from sqlalchemy import Integer, String
from sqlalchemy import sql, select, join, desc
from sqlalchemy import and_
import string

# Creating an engine object for database
engine = create_engine('sqlite://world.sqlite')
# Connecting to database
conn = engine.connect()

